---
Name: googlemaproutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'googlemap//$Action/$OwnerID/$Title' : 'GoogleMapDataResponse'
    'googlemapextensive//$Action/$OwnerID/$Title/$Latitude/$Longitude/$Filter' : 'GoogleMapDataResponse'
