---
Name: googlemaproutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'googlemap//$Action/$OwnerID/$Title' : 'GoogleMapDataResponse'
    'googlemapextensive//$Action/$OwnerID/$Title/$Longitude/$Latitude/$Filter' : 'GoogleMapDataResponse'
